version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
        environment:
          - APP_DEBUG: true
          - APP_ENV: testing
          - DB_CONNECTION: mysql
          - DB_HOST: mysql
          - DB_PORT: 5432
          - DB_DATABASE: default
          - DB_USERNAME: default
          - DB_PASSWORD: secret

      - image: circleci/mysql:5.7-ram
        environment:
          - MYSQL_DATABASE: default
          - MYSQL_USER: default
          - MYSQL_PASSWORD: secret
    steps:
      - checkout

      - run: sudo apt update
      - run: sudo docker-php-ext-install pdo_mysql

      - run: sudo composer self-update --1
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run dev

      - run: echo "APP_KEY=" > .env.testing
      - run: php artisan key:generate
      - run: php artisan migrate

      - run:
          name: php test
          command: vendor/bin/phpunit